name: ghcr automated
on:
  push

jobs:
  run-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: config docker and push
        run : |
          docker login --username J-Saeedi --password ${{secrets.GH_PAT}} ghcr.io
          docker build . --tag ghcr.io/J-Saeedi/iran_profile_for_internet:latest
          docker push ghcr.io/J-Saeedi/iran_profile_for_internet:latest
          
    
